version: "3.7"

services:

  evcommunities-gui-backend:
    image: ghcr.io/evcommunities/gui-backend:latest
    build:
      context: Node-backend
      dockerfile: Dockerfile
    container_name: evcommunities-gui-backend
    restart: always
    ports:
      - ${EVC_GUI_BACKEND_PORT:-7001}:7001
    environment:
      LOGREADER_API: ${LOGREADER_API:-http://localhost:8080}
      SIMULATION_STARTER: ${SIMULATION_STARTER:-http://localhost:8500/}
      PRIVATE_TOKEN: ${PRIVATE_TOKEN}
    networks:
      - evcommunities_demo

  evcommunities-gui-frontend:
    image: ghcr.io/evcommunities/gui-frontend:latest
    build:
      context: React-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_EVC_GUI_BACKEND: ${NEXT_PUBLIC_EVC_GUI_BACKEND}
    container_name: evcommunities-gui-frontend
    depends_on:
      - evcommunities-gui-backend
    restart: always
    ports:
      - ${EVC_GUI_FRONTEND_PORT:-3000}:3000
    networks:
      - evcommunities_demo

networks:
  evcommunities_demo:
    name: evcommunities_demo
